### ISSUE TITLE
Is it possible to have a `cargo bench --lib` equivalent with this crate?

### ISSUE THREAD

**Issue by kamalmarhubi** [bluss/bencher#3]
The benefits of `cargo bench --lib` are that benchmarks can run on unexported functions. It looks to me like not using the harness means that will be difficult or impossible, but I wanted to make sure.

**Comment by bluss** [comment]
I've only looked at that now, briefly: It requires disabling the test harness, so with tests & benchmarks being handled together like they are, the approach in this library does not help (we've removed all the testing code!).

It works, sort of, but it requires putting benchmark_main!() in the crate root and the benchmark_group!()s in their respective modules, and it clobbers in-crate testing.

Since benchmarking has been unstable, I've only ever used it separated out in benches/ before..

There's https://github.com/SimonSapin/rustc-test too, which I didn't find until after I did this crate.

**Comment by kamalmarhubi** [comment]
Thanks @bluss! I'll take a look at Simon's crate as well.
